import { icons, type LucideIcon } from 'lucide-react';

type MaterialIconProps = {
  name: string;
  className?: string;
};

const iconMap: Record<string, keyof typeof icons> = {
  account_balance_wallet: 'WalletCards',
  add: 'Plus',
  analytics: 'ChartNoAxesColumnIncreasing',
  arrow_downward: 'ArrowDown',
  arrow_forward: 'ArrowRight',
  assessment: 'ClipboardCheck',
  assignment_ind: 'UserCheck',
  assignment_turned_in: 'ClipboardCheck',
  auto_awesome: 'Sparkles',
  auto_stories: 'BookOpenCheck',
  biotech: 'Dna',
  bolt: 'Zap',
  bubbles: 'Bubbles',
  calculate: 'Calculator',
  calendar_month: 'CalendarDays',
  calendar_today: 'Calendar',
  call: 'Phone',
  card_giftcard: 'Gift',
  card_membership: 'BadgeCheck',
  category: 'Shapes',
  check: 'Check',
  check_circle: 'CircleCheck',
  checklist: 'ListChecks',
  checklist_rtl: 'ListChecks',
  chevron_right: 'ChevronRight',
  dashboard_customize: 'LayoutDashboard',
  description: 'FileText',
  devices: 'MonitorSmartphone',
  diversity_3: 'Users',
  done: 'Check',
  done_all: 'CheckCheck',
  download: 'Download',
  draw: 'PenLine',
  edit_note: 'FilePenLine',
  electric_bolt: 'Zap',
  emoji_objects: 'Lightbulb',
  expand_more: 'ChevronDown',
  experiment: 'FlaskConical',
  fact_check: 'ClipboardCheck',
  format_quote: 'Quote',
  forum: 'MessagesSquare',
  functions: 'SquareFunction',
  grade: 'BadgeCheck',
  group_work: 'Blocks',
  history: 'History',
  history_edu: 'ScrollText',
  home_work: 'House',
  hub: 'Network',
  library_books: 'LibraryBig',
  lightbulb: 'Lightbulb',
  list_alt: 'ListChecks',
  location_on: 'MapPin',
  lock: 'Lock',
  mail: 'Mail',
  map: 'Map',
  menu_book: 'BookOpen',
  monitoring: 'ChartNoAxesCombined',
  north_east: 'ArrowUpRight',
  open_in_new: 'ExternalLink',
  payments: 'WalletCards',
  person: 'User',
  person_search: 'UserRoundSearch',
  picture_as_pdf: 'FileText',
  play_arrow: 'Play',
  psychology: 'Brain',
  psychology_alt: 'BrainCircuit',
  public: 'Globe',
  query_stats: 'ChartNoAxesColumnIncreasing',
  quiz: 'CircleHelp',
  record_voice_over: 'AudioLines',
  rocket_launch: 'Rocket',
  schedule: 'Clock',
  schema: 'Workflow',
  school: 'GraduationCap',
  science: 'FlaskConical',
  sentiment_satisfied: 'Smile',
  sentiment_very_satisfied: 'SmilePlus',
  sms: 'MessageSquare',
  spellcheck: 'SpellCheck',
  star: 'Star',
  stars: 'Sparkles',
  task_alt: 'BadgeCheck',
  theater_comedy: 'Theater',
  timer: 'Timer',
  trending_flat: 'MoveRight',
  trending_up: 'TrendingUp',
  tune: 'SlidersHorizontal',
  update: 'RefreshCw',
  verified: 'BadgeCheck',
  verified_user: 'ShieldCheck',
  visibility: 'Eye',
  visibility_off: 'EyeOff',
  wb_sunny: 'Sun',
  workspace_premium: 'Award',
};

export default function MaterialIcon({ name, className = '' }: MaterialIconProps) {
  const Icon = (icons[iconMap[name] ?? 'CircleHelp'] ?? icons.CircleHelp) as LucideIcon;

  return (
    <Icon
      aria-hidden="true"
      className={`inline-block h-[1em] w-[1em] shrink-0 ${className}`}
      strokeWidth={2.25}
    />
  );
}
